---
title: "Упражнение №1"
author: "Маркин Артем"
date: "21 02 2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library('rvest')

url.1 <- 'https://market.yandex.ru/catalog--kholodilniki/71639/list?cpa=0&hid=15450081&lr=213&onstock=1&local-offers-first=0'
url.2 <- 'https://market.yandex.ru/catalog--kholodilniki/71639/list?cpa=0&hid=15450081&onstock=1&page=2&local-offers-first=0'
webpage.1 <- read_html(url.1)
webpage.2 <- read_html(url.2)

## Название холодильника
names1 <- webpage.1 %>% html_nodes(".cLo1fZHm2y") %>% html_text
names2 <- webpage.2 %>% html_nodes(".cLo1fZHm2y") %>% html_text
names <- c(names1, names2)
names

## Описание холодильника
description1 <- webpage.1 %>% html_nodes("._2_oj-OEI-o") %>% html_text
description2 <- webpage.2 %>% html_nodes("._2_oj-OEI-o") %>% html_text
description <- c(description1, description2)
description

## Цена холодильника
price1 <- webpage.1 %>% html_nodes("._3f2ZtYT7NH") %>% html_text
price2 <- webpage.2 %>% html_nodes("._3f2ZtYT7NH") %>% html_text
price <- c(price1, price2)
price

# Оставляем только числа
price <- gsub("[^[:digit:]]", "", price)
# Меняем тип со строки в числа
price <- as.numeric(price)
price

## Рейтинг холодильника
# функция перебора тегов внутри тегов более высокого уровня
get_tags <- function(node){
  # найти все теги с рейтингом
  raw_data <- html_nodes(node, selector) %>% html_text
  # значения нулевой длины меняем на пропуски
  data_NAs <- ifelse(length(raw_data) == 0, NA, raw_data)
}

selector <- '._1iKHblnc3a'

# Парсим рейтинг с первой страницы
doc1 <- html_nodes(webpage.1, '._1B9w_GzQuM')
rating1 <- sapply(doc1, get_tags)
# Парсим рейтинг со второй страницы
doc2 <- html_nodes(webpage.2, '._1B9w_GzQuM')
rating2 <- sapply(doc2, get_tags)

rating <- c(rating1, rating2)
# Превращаем строку в число
rating <- as.numeric(rating)
rating

## Количество отзывов
selector <- '.KdrkCVDrVm'
doc1 <- html_nodes(webpage.1, '._1B9w_GzQuM')
feedback1 <- sapply(doc1, get_tags)
doc2 <- html_nodes(webpage.2, '._1B9w_GzQuM')
feedback2 <- sapply(doc2, get_tags)

feedback <- c(feedback1, feedback2)
# Оставляем только числа
feedback <- gsub("[^[:digit:]]", "", feedback)
# Строку в число
feedback <- as.numeric(feedback)
feedback

data.dir <- './data'

# Создаём директорию для данных, если она ещё не существует:
if (!file.exists(data.dir)) {
  dir.create(data.dir)
}

# Создаём файл с логом загрузок, если он ещё не существует:
log.filename <- './data/download.log'
if (!file.exists(log.filename)) file.create(log.filename)

df <- data.frame(Name = names, Description = description, 
                 Price = price, Rating = rating,  Feedback = feedback)

# Записываем в .csv
write.csv(df, file = './data//yandex_market.csv', row.names = F)
# запись в лог
write(paste('Файл "yandex_market.csv" создан:', Sys.time()), 
      file = log.filename, append = T)
```